<?php

namespace AdminBundle\Repository;

/**
 * ClientsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientsRepository extends \Doctrine\ORM\EntityRepository
{
     // HOME
     public function findClients($formData)
     {
        $query = $this->createQueryBuilder('c');
        
        if (isset($formData["keyword"]) && $formData["keyword"] != "") {
            $query->where('c.name LIKE :_keyword');
            $query->orWhere('c.lastname LIKE :_keyword');
            $query->orWhere('c.email LIKE :_keyword');
            $query->orWhere('c.observation LIKE :_keyword');
            $query->setParameter('_keyword', '%'.$formData["keyword"].'%');
        }

        if (isset($formData["groups"]) && $formData["groups"] != "") {
            $query->leftJoin('c.clientsGroups','cg');
            $query->andWhere('cg.groups in (:_groups)');
            $query->setParameter('_groups', $formData["groups"]);
        }

        $result = $query->getQuery()->execute();

        return $result;
     }

}
