<?php

namespace AdminBundle\Repository;

/**
 * GroupsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientsGroupsRepository extends \Doctrine\ORM\EntityRepository
{
}
